#- name: apiserver install
#  gather_facts: false
#  hosts: apiserver
#  roles:
#    - apiserver-install

- name: "安装nginx代理和keepalived"
  gather_facts: false
  hosts: apiserver-nginx
  roles:
    - apiserver-install