- name: "发送scheduler 启动脚本"
  copy:
    src: files/kube-scheduler-startup.sh
    dest: /opt/kubernetes/server/bin/kube-scheduler-startup.sh
    mode: 0777

- name: "发送supervisor控制文件"
  copy:
    src: files/kube-scheduler.ini
    dest: /etc/supervisord.d/kube-scheduler.ini

- name: "创建scheduler 日志目录"
  file:
    path: /data/logs/kubernetes/kube-scheduler
    state: directory

- name: "启动supervisord，启动controller-manager进程"
  shell: "/usr/bin/supervisorctl update"
  args:
    chdir: /opt/kubernetes/server/bin/