- name: mkdir docker_root dir
  file:
    path: /data/docker
    state: directory

- name: copy rpm to remote
  copy:
    src: /etc/ansible/package/docker-ce-18.06.3.ce-3.el7.x86_64.rpm
    dest: /data/docker

- name: copy rpm to remote
  copy:
    src: /etc/ansible/package/docker-distribution-2.6.2-2.git48294d9.el7.x86_64.rpm
    dest: /data/docker

- name: install docker rpm
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - /data/docker/docker-ce-18.06.3.ce-3.el7.x86_64.rpm
    - /data/docker/docker-distribution-2.6.2-2.git48294d9.el7.x86_64.rpm

- name: mkdir /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: copy docker-daemon.json to remote
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json

- name: start docker
  systemd:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes

- name: login docker registry
  shell: "docker login http://harbor.od.com  -u 'admin' -p 'Harbor12345' "   #fixme username password 与配置文件中相同
