- name: stop SElinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: "SELINUX=disabled"
    state: present

- name: stop swapoff
  shell: swapoff -a

- name: modify /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/centos-swap'
    state: absent

- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: install dependency package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - net-tools
    - telnet
    - tree
    - nmap
    - sysstat
    - lrzsz
    - dos2unix
    - bind-utils

- name: change DNS addresses
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    line: '10.4.7.11'
    state: present

- name: add host.com to resolv.conf
  shell: 'sed -i "2isearch host.com"  /etc/resolv.conf '

- name: change /etc/rc.local
  lineinfile:
    path: /etc/rc.d/local
    line: "sed -i \"2isearch host.com\"  /etc/resolv.conf "
    state: present

- name: change rc.local scripe mode
  shell: "chmod 777 /etc/rc.d/rc.local"